datasets:
  test:
    path: C:\Users\Yonatan\Desktop\minislam-master\minislam-master\eval\example.mp4
    fx: 718.856
    fy: 718.856
    cx: 607.2
    cy: 185.2
    w: 1241
    h: 376
  test2:
    path: eval/test1.mp4
    fx: 718.856
    fy: 718.856
    cx: 607.2
    cy: 185.2
    w: 1241
    h: 376
