name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Lint
      run: python -m pylint minislam/